<script setup lang="ts">
import {ref, watch} from 'vue'
import {ElMessage} from 'element-plus'
import type {Evaluation, Evidence} from '../types'
defineProps<{value: Evaluation}>()
const selected = ref<Evidence | null>(null), levelsOpen = ref(false)
const selectedTask = ref<Evaluation['follow_ups'][number] | null>(null), taskDraft=ref('')
watch(selectedTask,t=>{taskDraft.value=t?.body || t?.detail || ''})
async function copyTask(){try{await navigator.clipboard.writeText(taskDraft.value);ElMessage.success('任务文案已复制')}catch{ElMessage.error('复制失败，请手动选择文案复制')}}
const levels = ['成果形成与验证', '局部作用验证', '外部应用验证', '专业方向显著影响', '领域基础能力', '重大引领影响']
</script>
<template>
  <div class="report">
    <p v-if="value.review_window" class="muted">{{value.review_window}}</p>
    <el-alert v-if="value.is_demo" title="演示结果 · 当前使用模拟评价，内容不代表真实科研结论。" type="warning" :closable="false" show-icon />
    <el-alert v-if="!value.is_demo && value.evaluation_status && value.evaluation_status!=='formal'" :title="value.evaluation_status==='needs_scope_confirmation' ? '待确认成果范围，请管理员确认候选并重新评价。' : value.evaluation_status==='insufficient_project_context' ? '缺少项目上下文，不能给出正式等级。' : '初步评价 / 待补证，尚未形成正式等级。'" type="warning" :closable="false"/><div class="report-layout report-v14"><aside class="panel report-index"><div class="eyebrow">ACHIEVEMENT</div><h3>{{value.category}}</h3><p v-if="value.project_name">{{value.project_name}}</p><div v-if="value.evaluation_status==='needs_scope_confirmation'" class="scope-candidates"><strong>识别到的候选成果</strong><p v-for="c in value.candidates" :key="c">{{c}}</p></div><p>{{value.title}}</p><div class="keyword-list"><span v-for="k in value.keywords" :key="k">{{k}}</span></div><hr><h3>送检材料与证据索引 <small>{{value.evidence.length}}</small></h3><button v-for="ev in value.evidence" :key="ev.id" class="evidence-index" @click="selected=ev"><div><strong>{{ev.title}}</strong><small>{{ev.source}}</small></div><b>↗</b></button><p v-if="!value.evidence.length" class="muted">尚无可展示的证据</p></aside>
      <section class="panel report-summary"><div class="report-block-title"><span class="section-no">①</span>影响力等级判断</div><h1>{{value.title}}</h1><p class="achievement-summary">{{value.summary}}</p><div class="grade-area"><div class="grade-box"><span>当前影响等级 <button class="help-button" @click="levelsOpen=true" aria-label="查看六级影响力标尺">?</button></span><div class="grade">{{value.level ? `L${value.level}` : '待评'}}<small v-if="value.level">/ 6</small></div><strong>{{value.level_name}}</strong></div><div><h3>评价依据</h3><ul class="reasons"><li v-for="(r,i) in value.reasons" :key="i">{{r}}<div><button v-for="id in value.reason_evidence_refs?.[i] || []" :key="id" class="evidence-tag" @click="selected=value.evidence.find(e=>e.id===id)||null">{{value.evidence.find(e=>e.id===id)?.title}}</button></div></li></ul></div></div><p v-if="value.boundary_gap" class="muted">{{value.boundary_gap}}</p><div v-if="value.upgrades?.length" class="report-upgrades"><div v-for="(u,i) in value.upgrades" :key="u.target_level"><h3>提升{{i+1}}级 → L{{u.target_level}} · {{u.level_name}}</h3><p>需要做到：{{u.need}}</p><small>佐证材料：{{u.proof_materials.join('；')}}</small></div></div></section>
      <section class="panel comparison"><div class="panel-heading"><h2><span class="section-no">②</span>关键判断与证据</h2><span>材料主张 × 评价核验</span></div><div class="table-scroll"><table><thead><tr><th>关键问题</th><th>项目方材料 / 主张</th><th>评价核验</th></tr></thead><tbody><tr v-for="row in value.dimensions" :key="row.topic"><th>{{row.topic}}</th><td>{{row.claim}}<div><button v-for="id in row.project_evidence_ids || []" :key="id" class="evidence-tag" @click="selected=value.evidence.find(e=>e.id===id)||null">{{value.evidence.find(e=>e.id===id)?.title}}</button></div></td><td><p>{{row.assessment}}</p><button v-for="id in row.evidence_ids" :key="id" class="evidence-tag" @click="selected=value.evidence.find(e=>e.id===id) || null">{{value.evidence.find(e=>e.id===id)?.title}} ↗</button></td></tr></tbody></table></div></section>
      <section class="panel follow-panel"><div class="panel-heading"><h2><span class="section-no">③</span>下一步任务</h2><span>让下一步更明确</span></div><div v-for="(item, i) in value.follow_ups" :key="i" class="follow-item"><span class="follow-number">0{{i+1}}</span><div><h3>{{item.title}}</h3><p class="task-excerpt">{{item.detail}}</p></div><button class="task-detail-button" @click="selectedTask=item">查看任务</button></div><p v-if="!value.follow_ups.length" class="muted padded">当前暂无后续事项</p></section>
    </div>
    <el-dialog :model-value="!!selectedTask" @close="selectedTask=null" title="下一步任务详情" width="min(700px, 94vw)"><template v-if="selectedTask"><h2>{{selectedTask.title}}</h2><el-input v-model="taskDraft" type="textarea" :rows="12" aria-label="任务文案"/><div class="task-draft-actions"><el-button @click="taskDraft=selectedTask.body || selectedTask.detail">恢复原文</el-button><el-button type="primary" @click="copyTask">复制任务文案</el-button></div></template></el-dialog>
    <el-dialog :model-value="!!selected" @close="selected=null" title="证据详情" width="min(760px, 94vw)"><template v-if="selected"><div class="eyebrow">{{selected.id}} · {{selected.source}}</div><h2>{{selected.title}}</h2><p class="muted">{{selected.locator}}</p><blockquote>{{selected.excerpt}}</blockquote><p v-if="selected.supports">能证明：{{selected.supports}}</p><p v-if="selected.does_not_prove">不能证明：{{selected.does_not_prove}}</p><a v-if="selected.url" :href="selected.url" target="_blank" rel="noopener noreferrer" class="text-link">打开原始来源 ↗</a></template></el-dialog>
    <el-dialog v-model="levelsOpen" title="六级影响力标尺" width="min(600px, 94vw)"><div v-for="(name, i) in levels" :key="name" class="level-row" :class="{current: value.level===i+1}"><strong>L{{i+1}}</strong><span>{{name}}</span></div><p class="muted">采用吴老师 v2 六级影响力标尺；等级由真实作用与证据判断，不对七维求平均。</p></el-dialog>
  </div>
</template>
