<script setup lang="ts">
defineProps<{value:{comparison:string;current_level?:string|null;coordination?:{status:string;review_items?:{field:string;action:string;reason:string}[];quality?:{revision_notes:string}};levels:{management_level:string|null;dimension_level:string|null;scope_level:string|null};differences:{field:string;management:string|null;dimensions:string|null;management_reason?:string;dimension_reason?:string;review_action?:string}[]}}>()
const names:Record<string,string>={impact_level:'实际影响等级',D1:'问题解决与先进性',D2:'原创与项目新增',D3:'学术影响',D4:'开放复用',D5:'真实应用',D6:'主线集成',D7:'外部认可'}
function name(field:string){return (names[field.replace('_state','')]||field)+(field.endsWith('_state')?' · 证据状态':'')}
</script>
<template><section class="panel padded unified-evaluation"><div class="review-heading"><div><small>主报告结论</small><h2>{{value.levels.management_level||'暂不定级'}} <span>以管理者报告为准</span></h2></div><span class="review-status">{{value.coordination?.status==='completed'?'已完成内部协调':'历史底稿／尚未执行新增协调'}}</span></div><p class="muted">七维检查为主报告提供审查依据。仍有异议时保留具体理由，系统一致也不等于专家确认。</p><div class="review-count">{{value.differences.length ? '保留 '+value.differences.length+' 项审查差异' : '当前未发现等级或证据状态差异'}}</div><details v-for="d in value.differences" :key="d.field"><summary>{{name(d.field)}}<span>查看依据</span></summary><div class="review-reasons"><div><h3>管理者判断</h3><p>{{d.management_reason||'原底稿未单列理由'}}</p></div><div><h3>内部审查意见</h3><p>{{d.dimension_reason||'原底稿未单列理由'}}</p></div></div><p v-if="value.coordination?.review_items?.find(r=>r.field===d.field)" class="coordination-reason"><strong>协调处理：</strong>{{value.coordination.review_items.find(r=>r.field===d.field)?.reason}}</p><p class="muted">{{d.review_action}}</p></details><details v-if="value.coordination?.status==='completed'"><summary>协调记录与表达检查<span>展开</span></summary><p v-for="r in value.coordination.review_items" :key="r.field"><strong>{{name(r.field)}} · {{r.action==='revised'?'已修订':'保留主报告判断'}}</strong><br>{{r.reason}}</p><p>{{value.coordination.quality?.revision_notes}}</p></details></section></template>
<style scoped>
.unified-evaluation{margin-bottom:20px;line-height:1.8;overflow-wrap:anywhere}.review-heading{display:flex;justify-content:space-between;align-items:center;gap:16px;flex-wrap:wrap}.review-heading h2{margin:4px 0;font-size:30px;color:#235577}.review-heading h2 span{font-size:14px;font-weight:500}.review-heading small,.muted{color:#617587;font-size:13px}.review-status,.review-count{font-size:13px;color:#356c72;background:#edf6f5;border-radius:6px;padding:8px 12px}.review-count{margin:18px 0;background:#f1f5f9;color:#435c72}details{border-top:1px solid #e1e8ee;padding:14px 0}summary{cursor:pointer;font-weight:600}summary span{float:right;color:#617587;font-size:12px;font-weight:400}.review-reasons{display:grid;grid-template-columns:1fr 1fr;gap:24px}.review-reasons h3{font-size:13px;color:#617587}.review-reasons p{font-size:14px}.coordination-reason{background:#f4f8fa;padding:12px}@media(max-width:700px){.review-reasons{grid-template-columns:1fr;gap:0}}
</style>
