import {test,expect} from '@playwright/test'

test('真实拉曼草稿可预览且未公开',async({page})=>{
  const resultId=process.env.LIVE_RESULT_ID, pipelineId=process.env.LIVE_PIPELINE_ID
  test.skip(!resultId||!pipelineId||!process.env.E2E_ADMIN_PASSWORD,'需要显式指定本次真实结果和工作流')
  await page.goto('/login')
  await page.getByLabel('账号',{exact:true}).fill('admin')
  await page.getByLabel('密码',{exact:true}).fill(process.env.E2E_ADMIN_PASSWORD!)
  await page.getByRole('button',{name:'登录',exact:true}).click()
  await expect(page.getByRole('heading',{name:'评价工作台'})).toBeVisible()
  const results=await (await page.request.get('/api/admin/results')).json()
  const index=results.findIndex((r:any)=>r.id===resultId)
  expect(index).toBeGreaterThanOrEqual(0)
  const result=results[index];expect(result.status).toBe('draft');expect(result.payload.is_demo).toBe(false)
  await page.getByRole('tab',{name:'结果与审核',exact:true}).click()
  await page.locator('#pane-results .el-table__body-wrapper tbody tr').nth(index).getByRole('button',{name:'预览 / 编辑'}).click()
  const dialog=page.getByRole('dialog',{name:'评价结果审核',exact:true})
  await expect(dialog.locator('.report-summary h1')).toHaveText(result.title)
  await expect(dialog.locator('.grade').first()).toContainText(result.payload.level ? `L${result.payload.level}` : '待评')
  await page.screenshot({path:'test-results/raman-real-report.png',fullPage:true,animations:'disabled'})
  expect((await page.request.get(`/api/results/${resultId}`)).status()).toBe(404)
  await dialog.getByRole('button',{name:'Close this dialog',exact:true}).click()
  await expect(dialog).not.toBeVisible()
  await page.goto(`/admin?pipeline=${pipelineId}`)
  const workflow=page.getByRole('dialog',{name:'完整评价工作流',exact:true});await expect(workflow).toBeVisible()
  await workflow.getByRole('button',{name:'预览v19独立底稿',exact:true}).click()
  const v19=page.getByRole('dialog',{name:'v19双层评估 · 独立底稿',exact:true})
  await expect(v19.getByText('特定层',{exact:true})).toBeVisible()
  await expect(v19.getByText('全局层',{exact:true})).toBeVisible()
  await page.screenshot({path:'test-results/raman-v19-real-report.png',fullPage:true,animations:'disabled'})
})
