import {test, expect} from '@playwright/test'

test('用户固定表单、已有成果联想和评价结果', async({page})=>{
  const errors:string[]=[]; page.on('pageerror',e=>errors.push(e.message))
  await page.goto('/')
  await expect(page.getByRole('heading',{name:'选择成果，开始评价。'})).toBeVisible()
  await page.screenshot({path:'test-results/home-desktop.png',fullPage:true})
  const first=page.locator('.featured-button').first()
  const title=await first.locator('h3').innerText()
  await first.click()
  await expect(page.getByLabel('已有成果')).toHaveValue(/.+/)
  await page.getByLabel('评价任务').selectOption({label:'外部应用证据核验'})
  await page.getByLabel('补充说明').fill('只核验已有外部应用证据。')
  await page.getByRole('button',{name:'开始查询'}).click()
  await expect(page.getByRole('heading',{name:/查询结果/})).toBeVisible()
  await expect(page.getByText('外部应用证据核验 · 表单已保存')).toBeVisible()
  await page.locator('.fixed-results .result-card').first().click()
  await expect(page.locator('.report-summary h1')).toHaveText(title)
  await page.screenshot({path:'test-results/result-desktop.png',fullPage:true})
  await page.getByRole('link',{name:'我的需求',exact:true}).click()
  await expect(page.locator('.query-history').getByText('只核验已有外部应用证据。')).toBeVisible()
  expect(errors).toEqual([])
})

test('联想键盘补全、修改后失效和服务端格式限制',async({page})=>{
  await page.goto('/')
  const input=page.getByRole('combobox',{name:'已有成果'})
  await input.fill('拉曼')
  await expect(page.getByRole('option').first()).toBeVisible()
  await input.press('ArrowDown'); await input.press('Enter')
  await expect(input).not.toHaveValue('拉曼')
  await page.getByRole('button',{name:'开始查询'}).click()
  await expect(page.getByRole('heading',{name:/查询结果/})).toBeVisible()
  await input.fill('完全不存在的项目')
  await expect(page.getByText(/没有匹配的已发布成果/)).toBeVisible()
  await page.getByRole('button',{name:'开始查询'}).click()
  await expect(page.getByText('请从联想列表中选择一个已有成果', {exact:false})).toBeVisible()
  const lookup=page.waitForResponse(r=>r.url().includes('/projects/suggestions?q=') && decodeURIComponent(r.url()).includes('快速提交未收录项目'))
  await input.fill('快速提交未收录项目')
  await page.getByRole('button',{name:'开始查询'}).click()
  await lookup
  await expect(page.getByText('请从联想列表中选择一个已有成果', {exact:false})).toBeVisible()
  const response=await page.request.post('/api/search',{data:{query:'绕过表单'}})
  expect(response.status()).toBe(422)
})

test('管理端材料评价发布后可在固定表单选中',async({page})=>{
  const password=process.env.E2E_ADMIN_PASSWORD
  test.skip(!password,'Set E2E_ADMIN_PASSWORD')
  const title=`表单流程验证-${Date.now()}`
  await page.goto('/login')
  await page.getByLabel('账号',{exact:true}).fill('admin')
  await page.getByLabel('密码',{exact:true}).fill(password!)
  await page.getByRole('button',{name:'登录',exact:true}).click()
  await expect(page.getByRole('heading',{name:'评价工作台'})).toBeVisible()
  const request=await page.request.post('/api/admin/search',{data:{query:title}})
  expect(request.ok()).toBeTruthy()
  await page.getByRole('button',{name:'刷新数据'}).click()
  await page.getByRole('row').filter({hasText:title}).getByRole('button',{name:'吴老师单项评价'}).click()
  await page.getByTestId('evaluation-adapter').click()
  await page.getByRole('option',{name:'模拟评价（仅用于流程演示）',exact:true}).click()
  await page.locator('#material-file').setInputFiles({name:'form-evidence.txt',mimeType:'text/plain',buffer:Buffer.from('固定表单流程演示材料，尚需正式规则核验。')})
  await expect(page.getByText('材料上传并解析完成')).toBeVisible()
  await page.getByRole('button',{name:'创建评价任务',exact:true}).click()
  await expect(page.getByRole('row').filter({hasText:title}).getByText('已生成草稿')).toBeVisible({timeout:30000})
  await page.getByRole('tab',{name:'结果与审核'}).click()
  await page.getByRole('row').filter({hasText:title}).getByRole('button',{name:'发布',exact:true}).click()
  await page.getByRole('button',{name:'确认发布'}).click()
  await expect(page.getByText('已发布，用户可查询此结果')).toBeVisible()
  await page.goto('/')
  await page.getByRole('combobox',{name:'已有成果'}).fill(title)
  await page.getByRole('option').filter({hasText:title}).click()
  await page.getByRole('button',{name:'开始查询'}).click()
  await page.locator('.fixed-results .result-card').click()
  await expect(page.locator('.report-summary h1')).toHaveText(title)
  await page.getByRole('button',{name:/form-evidence/}).first().click()
  await expect(page.getByRole('dialog').getByText('固定表单流程演示材料，尚需正式规则核验。')).toBeVisible()
})

test('移动端首页布局与查询',async({page})=>{
  await page.setViewportSize({width:390,height:844})
  await page.goto('/')
  await page.getByLabel('已有成果').fill('不存在的项目')
  await page.getByRole('button',{name:'开始查询'}).click()
  await expect(page.getByText('请从联想列表中选择一个已有成果')).toBeVisible()
  await page.getByLabel('已有成果').fill('')
  await page.locator('.featured-button').first().click()
  await page.getByRole('button',{name:'开始查询'}).click()
  await expect(page.getByRole('heading',{name:/查询结果/})).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  await page.screenshot({path:'test-results/home-mobile.png',fullPage:true})
})
