<script setup lang="ts">
import {ref, onMounted, onUnmounted} from 'vue'
import {useRouter,useRoute} from 'vue-router'
import {ElMessage, ElMessageBox} from 'element-plus'
import {api, post, statusNames, formatDate} from '../api'
import type {User, Ticket, Material, Task, Result, Evaluation} from '../types'
import EvaluationReport from '../components/EvaluationReport.vue'
import QueryHistory from '../components/QueryHistory.vue'
import PipelineWorkbench from '../components/PipelineWorkbench.vue'
const route=useRoute(), router=useRouter(), ready=ref(false), error=ref(''), tab=ref(typeof route.query.pipeline==='string'?'pipeline':'tickets'), busy=ref(false)
const overview=ref<Record<string,number>>({}), tickets=ref<Ticket[]>([]), materials=ref<Material[]>([]), tasks=ref<Task[]>([]), results=ref<Result[]>([]), audits=ref<{id:string;action:string;target:string;created_at:string}[]>([])
const adapters=ref<{name:string;version:string;label:string;available:boolean;configured:boolean;reason?:string}[]>([]), adapterName=ref(''), projectContext=ref(''), confirmedScope=ref('')
const title=ref(''), keywords=ref(''), materialIds=ref<string[]>([]), ticketId=ref(''), selected=ref<Result|null>(null), editor=ref(''), editMode=ref(false), preview=ref<Material|null>(null), versions=ref<{revision:number;payload:Evaluation;created_at:string}[]>([]), versionsOpen=ref(false), reviewOpen=ref(false), uploadSummary=ref('')
const uploadPurpose=ref('project')
const uploadRejected=ref<{filename:string;error:string}[]>([])
let timer: ReturnType<typeof setInterval> | undefined
async function load() {try {const [o,t,m,j,r,a]=await Promise.all([api<Record<string,number>>('/admin/overview'),api<Ticket[]>('/admin/tickets'),api<Material[]>('/admin/materials'),api<Task[]>('/admin/tasks'),api<Result[]>('/admin/results'),api<typeof audits.value>('/admin/audit')]); overview.value=o; tickets.value=t; materials.value=m; tasks.value=j; results.value=r; audits.value=a; error.value=''} catch(e){error.value=(e as Error).message}}
onMounted(async()=>{try {const user=await api<User>('/auth/me'); if(user.role!=='admin'){error.value='当前账户没有管理权限'; return} ready.value=true; adapters.value=await api('/admin/adapters'); adapterName.value=adapters.value.find(a=>a.configured)?.name || 'mock'; await load(); timer=setInterval(load,5000)} catch {router.replace({path:'/login',query:{redirect:route.fullPath}})}})
onUnmounted(()=>clearInterval(timer))
async function action(fn:()=>Promise<void>) {busy.value=true; try {await fn(); await load()} catch(e){if(e!=='cancel' && e!=='close') ElMessage.error((e as Error).message || String(e))} finally {busy.value=false}}
async function useTicket(t:Ticket) {await action(async()=>{ticketId.value=t.id;title.value=t.query;keywords.value=t.query;materialIds.value=[];projectContext.value='';confirmedScope.value='';const submission=await api<{payload:{project_name:string};material_ids:string[]}|null>(`/admin/submissions/${t.id}`);if(submission){materialIds.value=submission.material_ids;projectContext.value=submission.payload.project_name}tab.value='create'})}
async function upload(event:Event) {const input=event.target as HTMLInputElement; const files=Array.from(input.files || []); if(!files.length)return; await action(async()=>{const form=new FormData(); form.append('purpose',uploadPurpose.value); files.forEach(file=>form.append('files',file,file.webkitRelativePath || file.name)); const data=await api<{accepted:Material[];rejected:{filename:string;error:string}[];accepted_count:number;rejected_count:number}>('/admin/materials/batch',{method:'POST',body:form}); data.accepted.filter(m=>(m.purpose||'project')==='project').forEach(m=>materialIds.value.push(m.id)); uploadRejected.value=data.rejected; uploadSummary.value=`本次成功 ${data.accepted_count} 个，跳过或失败 ${data.rejected_count} 个`; if(data.rejected_count) ElMessage.warning(uploadSummary.value); else ElMessage.success('材料上传并解析完成')}); input.value=''}
async function createTask() {await action(async()=>{await post('/admin/tasks',{title:title.value,keywords:keywords.value.split(/[,，、\n]/).map(x=>x.trim()).filter(Boolean),material_ids:materialIds.value,ticket_id:ticketId.value||null,adapter:adapterName.value,project_context:projectContext.value,confirmed_scope:confirmedScope.value}); title.value=''; keywords.value=''; materialIds.value=[]; ticketId.value=''; tab.value='tasks'; ElMessage.success('已加入后台评价队列')})}
function openReview(row:Result) {selected.value=JSON.parse(JSON.stringify(row)); editor.value=JSON.stringify(row.payload,null,2); editMode.value=false; reviewOpen.value=true}
async function save() {await action(async()=>{if(!selected.value)return; const payload=JSON.parse(editor.value); selected.value=await api<Result>(`/admin/results/${selected.value.id}`,{method:'PUT',body:JSON.stringify({revision:selected.value.revision,payload})}); editor.value=JSON.stringify(selected.value.payload,null,2); editMode.value=false; ElMessage.success('草稿已校验并保存')})}
async function publish(row:Result) {await action(async()=>{await ElMessageBox.confirm(row.payload.is_demo?'这是模拟评价，发布后会保留醒目的演示标识。确认发布供流程体验？':'确认已核实评价依据并发布此结果？','审核发布',{confirmButtonText:'确认发布',cancelButtonText:'取消'}); const updated=await post<Result>(`/admin/results/${row.id}/publish`,{revision:row.revision}); if(selected.value?.id===row.id)selected.value=updated; ElMessage.success('已发布，用户可查询此结果')})}
async function withdraw(row:Result) {await action(async()=>{await ElMessageBox.confirm('撤回后用户将无法查询此结果，可以编辑后重新发布。','撤回结果',{confirmButtonText:'撤回',cancelButtonText:'取消'}); const updated=await post<Result>(`/admin/results/${row.id}/withdraw`,{revision:row.revision}); if(selected.value?.id===row.id)selected.value=updated; ElMessage.success('结果已撤回')})}
async function showVersions(row:Result){await action(async()=>{versions.value=await api(`/admin/results/${row.id}/versions`); versionsOpen.value=true})}
function exportJson(row:Result){const url=URL.createObjectURL(new Blob([JSON.stringify(row.payload,null,2)],{type:'application/json'})); const a=document.createElement('a');a.href=url;a.download=`evaluation-${row.id}.json`;a.click();URL.revokeObjectURL(url)}
const auditLabels:Record<string,string>={material_purpose_project:'标记为项目材料',material_purpose_reference:'标记为参考资料',material_purpose_instruction:'标记为流程说明',submit_outcome:'提交成果表单',pipeline_create:'创建完整工作流',pipeline_resume:'继续工作流',pipeline_amend:'补证后重评',pipeline_cancel:'取消工作流',pipeline_report_draft:'生成报告草稿',pipeline_report_refresh:'更新报告草稿',import_verified_live_test:'登记真实测试结果',upload_material:'上传材料',create_task:'创建评价任务',edit_result:'编辑草稿',publish_result:'审核发布',withdraw_result:'撤回结果',retry_task:'重试任务',close_ticket:'关闭需求'}
</script>
<template><div class="content-page admin-page"><div class="page-heading"><div><div class="eyebrow">MANAGEMENT WORKSPACE</div><h1>评价工作台</h1><p>从需求受理到审核发布，让每项成果都有完整的评价记录。</p></div><el-button @click="load" v-if="ready">刷新数据</el-button></div><el-alert v-if="error" :title="error" type="error" :closable="false"/><template v-if="ready"><div class="stats"><div v-for="[key,label] in [['tickets','待处理需求'],['tasks','运行中任务'],['drafts','待审核草稿'],['published','已发布成果']]" :key="key" class="panel stat"><span>{{label}}</span><strong>{{overview[key] ?? '—'}}</strong></div></div><el-alert :title="adapterName==='codex' ? 'Codex评价已接入 · 先定位成果并核验证据，生成草稿后需人工审核。' : '当前选择模拟评价，仅演示流程。新建评价时可切换Codex。'" type="info" :closable="false" show-icon />
  <el-tabs v-model="tab" class="admin-tabs">
    <el-tab-pane label="完整工作流" name="pipeline" lazy><PipelineWorkbench /></el-tab-pane>
    <el-tab-pane label="用户表单" name="queries" lazy><QueryHistory admin /></el-tab-pane>
    <el-tab-pane label="需求工单" name="tickets"><div class="panel padded"><el-table :data="tickets" empty-text="暂无待处理需求"><el-table-column prop="query" label="需求关键词" min-width="180"/><el-table-column label="状态" width="120"><template #default="{row}"><el-tag>{{statusNames[row.status]}}</el-tag></template></el-table-column><el-table-column label="提交时间" min-width="180"><template #default="{row}">{{formatDate(row.created_at)}}</template></el-table-column><el-table-column label="操作" width="280"><template #default="{row}"><el-button v-if="row.status==='pending'" type="primary" link @click="useTicket(row)">吴老师单项评价</el-button><el-button v-if="row.status==='pending'" link type="primary" @click="tab='pipeline'">完整工作流</el-button><el-button v-if="row.status==='pending'" link :disabled="busy" @click="action(async()=>{await post(`/admin/tickets/${row.id}/close`)})">关闭</el-button><RouterLink v-if="row.result_id" :to="`/results/${row.result_id}`" class="text-link">查看成果</RouterLink><span v-if="!row.result_id && row.status!=='pending'" class="muted">{{row.note || '请查看任务与审核列表'}}</span></template></el-table-column></el-table></div></el-tab-pane>
    <el-tab-pane label="吴老师单项评价" name="create"><div class="panel padded create-panel"><div><h2>材料与评价任务</h2><p class="muted">支持批量文件、文件夹和 ZIP；系统逐项解析并保留失败明细。</p></div><el-form label-position="top" @submit.prevent="createTask"><el-form-item label="关联需求"><el-select v-model="ticketId" clearable placeholder="可不关联，直接创建成果" class="full-width"><el-option v-for="t in tickets.filter(t=>t.status==='pending')" :key="t.id" :value="t.id" :label="t.query"/></el-select></el-form-item><el-form-item label="成果名称"><el-input v-model="title" placeholder="例如：拉曼指针" maxlength="200"/></el-form-item><el-form-item label="所属项目（可从材料自动识别）"><el-input v-model="projectContext" placeholder="例如：人工智能赋能有机化学 / 项目编号" maxlength="500"/></el-form-item><el-form-item label="已确认的成果范围（需要确认时填写）"><el-input v-model="confirmedScope" placeholder="按草稿候选填写完整成果名称，重新运行" maxlength="200"/></el-form-item><el-form-item label="检索关键词"><el-input v-model="keywords" placeholder="使用逗号分隔，例如：拉曼指针，拉曼，光谱"/></el-form-item><el-form-item label="选择评价材料"><el-select v-model="materialIds" multiple placeholder="从已上传材料中选择" class="full-width"><el-option v-for="m in materials.filter(m=>(m.purpose||'project')==='project')" :key="m.id" :value="m.id" :label="m.filename"/></el-select></el-form-item><div class="upload-box"><el-form-item label="本批资料用途"><el-select v-model="uploadPurpose"><el-option label="项目材料" value="project"/><el-option label="参考 / 既有评价" value="reference"/><el-option label="流程说明" value="instruction"/></el-select></el-form-item><label class="upload-label" for="material-file">＋ 选择文件 / 文件夹 / ZIP</label><input id="material-file" type="file" multiple accept=".txt,.md,.pdf,.docx,.xlsx,.zip" :disabled="busy" @change="upload"><label class="upload-label" for="material-folder">或选择整个文件夹</label><input id="material-folder" type="file" multiple webkitdirectory directory :disabled="busy" @change="upload"><p>单文件最大 200MB · 单批最多 200 个 · 总计 2GB · ZIP 解压后最多 5GB · PDF最多1000页 · 提取文本最多60万字 · 扫描件需先 OCR</p><p v-if="uploadSummary" class="upload-summary">{{uploadSummary}}</p><el-collapse v-if="uploadRejected.length"><el-collapse-item title="查看未导入文件及原因"><div v-for="(r,i) in uploadRejected" :key="i"><strong>{{r.filename}}</strong><p>{{r.error}}</p></div></el-collapse-item></el-collapse></div><el-form-item label="评价规则"><el-select data-testid="evaluation-adapter" v-model="adapterName" aria-label="评价规则" class="full-width"><el-option v-for="a in adapters" :key="a.name" :value="a.name" :label="a.label" :disabled="!a.available"/></el-select></el-form-item><el-button type="primary" native-type="submit" :loading="busy" :disabled="!title.trim() || !keywords.trim() || !materialIds.length">创建评价任务</el-button></el-form></div></el-tab-pane>
    <el-tab-pane label="材料库" name="materials"><div class="panel padded"><h2>资料入库</h2><p class="muted">原件、参考结果与流程说明分别保留；只有项目材料可以选择进入评测。当前列表显示最近200条。</p><el-select v-model="uploadPurpose" aria-label="入库资料用途"><el-option label="项目材料" value="project"/><el-option label="参考 / 既有评价" value="reference"/><el-option label="流程说明" value="instruction"/></el-select><label class="upload-label">选择文件 / ZIP<input type="file" multiple accept=".txt,.md,.pdf,.docx,.xlsx,.zip" :disabled="busy" @change="upload"/></label><label class="upload-label">选择文件夹<input type="file" multiple webkitdirectory :disabled="busy" @change="upload"/></label><p v-if="uploadSummary">{{uploadSummary}}</p><el-alert v-for="(r,i) in uploadRejected" :key="i" :title="`${r.filename}：${r.error}`" type="warning" :closable="false"/><el-table :data="materials" empty-text="请在新建评价中上传材料"><el-table-column prop="filename" label="文件" min-width="220"/><el-table-column label="资料用途" min-width="210"><template #default="{row}"><el-select :model-value="row.purpose||'project'" :disabled="busy" aria-label="资料用途" @change="(purpose:string)=>action(async()=>{await api(`/admin/materials/${row.id}/purpose`,{method:'PATCH',body:JSON.stringify({purpose})});if(purpose!=='project')materialIds=materialIds.filter(id=>id!==row.id)})"><el-option label="项目材料" value="project"/><el-option label="参考 / 既有评价" value="reference"/><el-option label="流程说明" value="instruction"/></el-select></template></el-table-column><el-table-column label="大小" width="110"><template #default="{row}">{{(row.size/1024).toFixed(1)}} KB</template></el-table-column><el-table-column label="上传时间" min-width="180"><template #default="{row}">{{formatDate(row.created_at)}}</template></el-table-column><el-table-column label="操作" width="160"><template #default="{row}"><el-button link @click="action(async()=>{preview=await api(`/admin/materials/${row.id}`)})">查看文本</el-button><a :href="`/api/admin/materials/${row.id}/download`" class="text-link">下载</a></template></el-table-column></el-table></div></el-tab-pane>
    <el-tab-pane label="评价任务" name="tasks"><div class="panel padded"><el-table :data="tasks" empty-text="暂无任务"><el-table-column prop="title" label="成果" min-width="180"/><el-table-column label="状态" width="135"><template #default="{row}"><el-tag :type="row.status==='failed'?'danger':row.status==='succeeded'?'success':'info'">{{statusNames[row.status]}}</el-tag></template></el-table-column><el-table-column prop="skill_version" label="规则版本" width="120"/><el-table-column prop="attempts" label="执行次数" width="100"/><el-table-column prop="error" label="错误信息" min-width="180"/><el-table-column label="操作" width="190"><template #default="{row}"><el-button v-if="row.status==='failed'" :disabled="busy" link type="primary" @click="action(async()=>{await post(`/admin/tasks/${row.id}/retry`)})">重试任务</el-button><el-button v-if="row.status==='succeeded'" link type="primary" @click="tab='results'">前往审核</el-button><a v-if="row.adapter==='codex' && row.status==='succeeded'" :href="`/api/admin/tasks/${row.id}/artifacts/evaluation-result.json`" class="text-link">完整底稿</a><a v-if="row.adapter==='codex' && row.status==='failed'" :href="`/api/admin/tasks/${row.id}/artifacts/stderr.log`" class="text-link">诊断日志</a></template></el-table-column></el-table></div></el-tab-pane>
    <el-tab-pane label="结果与审核" name="results"><div class="panel padded"><el-table :data="results" empty-text="任务完成后将在这里生成评价草稿"><el-table-column prop="title" label="成果" min-width="200"/><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="row.status==='published'?'success':'warning'">{{statusNames[row.status]}}</el-tag></template></el-table-column><el-table-column label="标识" width="90"><template #default="{row}"><span v-if="row.payload.is_demo" class="demo-badge">演示</span></template></el-table-column><el-table-column prop="revision" label="版本" width="70"/><el-table-column label="操作" min-width="310"><template #default="{row}"><el-button type="primary" link @click="openReview(row)">预览 / 编辑</el-button><el-button link :disabled="busy" @click="showVersions(row)">历史</el-button><el-button link @click="exportJson(row)">JSON</el-button><el-button v-if="row.status==='draft'" type="success" link :disabled="busy" @click="publish(row)">发布</el-button><el-button v-else type="warning" link :disabled="busy" @click="withdraw(row)">撤回</el-button></template></el-table-column></el-table></div></el-tab-pane>
    <el-tab-pane label="操作记录" name="audit"><div class="panel padded"><el-table :data="audits"><el-table-column label="操作" min-width="130"><template #default="{row}">{{auditLabels[row.action] || row.action}}</template></el-table-column><el-table-column prop="target" label="记录编号" min-width="280"/><el-table-column label="时间" min-width="180"><template #default="{row}">{{formatDate(row.created_at)}}</template></el-table-column></el-table></div></el-tab-pane>
  </el-tabs>
  <el-dialog v-model="reviewOpen" title="评价结果审核" width="min(1200px, 96vw)" :close-on-click-modal="false"><template v-if="selected"><div class="review-actions"><el-switch v-model="editMode" active-text="编辑 JSON" inactive-text="页面预览" :disabled="selected.status==='published'"/><span class="muted">版本 {{selected.revision}} · {{statusNames[selected.status]}}</span><el-button @click="exportJson(selected)">导出 JSON</el-button><el-button v-if="editMode" type="primary" :loading="busy" @click="save">校验并保存</el-button><el-button v-if="selected.status==='draft'" type="success" :disabled="busy || editMode" @click="publish(selected)">审核发布</el-button><el-button v-else type="warning" :disabled="busy" @click="withdraw(selected)">撤回以编辑</el-button></div><el-input v-if="editMode" v-model="editor" type="textarea" :rows="25" class="json-editor"/><EvaluationReport v-else :value="selected.payload"/></template></el-dialog>
  <el-dialog :model-value="!!preview" @close="preview=null" title="材料文本预览" width="min(850px, 94vw)"><template v-if="preview"><h3>{{preview.filename}}</h3><pre class="material-text">{{preview.text}}</pre></template></el-dialog>
  <el-dialog v-model="versionsOpen" title="评价历史版本" width="min(850px, 94vw)"><el-collapse><el-collapse-item v-for="v in versions" :key="v.revision" :title="`版本 ${v.revision} · ${formatDate(v.created_at)}`"><pre class="material-text">{{JSON.stringify(v.payload,null,2)}}</pre></el-collapse-item></el-collapse></el-dialog>
</template></div></template>
