<script setup lang="ts">
import {onMounted,onUnmounted,ref} from 'vue'
import {Search,ArrowRight,Files} from '@element-plus/icons-vue'
import {api,post} from '../api'
import type {Result} from '../types'
type Option={id:string;title:string;keywords:string[];category:string;is_demo:boolean}
const query=ref(''),selected=ref<Option|null>(null),options=ref<Option[]>([]),reports=ref<Result[]>([]),error=ref(''),busy=ref(false),loading=ref(true),focused=ref(false),active=ref(-1),searched=ref(false),detail=ref(''),taskType=ref('成果影响力评价')
let timer:ReturnType<typeof setTimeout>|undefined,sequence=0
async function load(){loading.value=true;try{reports.value=await api<Result[]>('/results');searched.value=false}catch(e){error.value=(e as Error).message}finally{loading.value=false}}
onMounted(load);onUnmounted(()=>{clearTimeout(timer);sequence++})
function change(){selected.value=null;focused.value=true;active.value=-1;const token=++sequence;clearTimeout(timer);if(!query.value.trim()){options.value=[];return}timer=setTimeout(async()=>{try{const items=await api<Option[]>('/projects/suggestions?q='+encodeURIComponent(query.value));if(token===sequence)options.value=items}catch(e){if(token===sequence)error.value=(e as Error).message}},180)}
function choose(item:Option){sequence++;clearTimeout(timer);selected.value=item;query.value=item.title;focused.value=false;error.value=''}
function move(amount:number){focused.value=true;active.value=Math.max(0,Math.min(options.value.length-1,active.value+amount))}
async function submit(){if(focused.value&&active.value>=0&&options.value[active.value]){choose(options.value[active.value]);return}if(!selected.value){error.value='请从下拉列表中选择一项成果。';return}busy.value=true;error.value='';try{const data=await post<{results:Result[]}>('/search',{project_id:selected.value.id,task_type:taskType.value,detail:detail.value});reports.value=data.results;searched.value=true;focused.value=false}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
function reset(){query.value='';selected.value=null;options.value=[];focused.value=false;error.value='';load()}
</script>
<template><div class="content-page library-page"><div class="page-heading"><div><h1>成果报告</h1></div><RouterLink to="/submit" class="secondary-link">提交新成果</RouterLink></div><form class="panel library-search" @submit.prevent="submit"><label for="report-search">成果名称或关键词</label><div class="search-line"><div class="search-combobox"><div class="field-wrap"><el-icon><Search/></el-icon><input id="report-search" v-model="query" role="combobox" autocomplete="off" aria-autocomplete="list" aria-controls="report-options" :aria-expanded="focused" :aria-activedescendant="active>=0?'report-option-'+active:undefined" placeholder="例如：拉曼、光谱、模型名称" @input="change" @focus="focused=!!query" @blur="focused=false" @keydown.down.prevent="move(1)" @keydown.up.prevent="move(-1)" @keydown.esc="focused=false"/><button v-if="query" type="button" class="clear-field" aria-label="清空查询" @click="reset">×</button></div><div v-if="focused&&query" id="report-options" class="suggestion-menu" role="listbox"><p v-if="!options.length" class="suggestion-empty">暂无匹配成果，可以换一个关键词。</p><button v-for="(option,i) in options" :id="'report-option-'+i" :key="option.id" type="button" role="option" :aria-selected="active===i" class="suggestion-item" :class="{highlighted:active===i}" @mousedown.prevent @click="choose(option)"><span><strong>{{option.title}}</strong><small>{{option.keywords.join('、')}}</small></span></button></div></div><el-button type="primary" native-type="submit" :loading="busy">查询报告</el-button><el-button v-if="searched" @click="reset">重置</el-button></div><details class="query-options"><summary>记录查询关注点（选填）</summary><div class="two-column-fields"><label>关注方向<select v-model="taskType"><option>成果影响力评价</option><option>技术先进性核验</option><option>外部应用证据核验</option></select></label><label>补充说明<input v-model="detail" maxlength="300" placeholder="例如：关注外部应用的证明材料"/></label></div></details><el-alert v-if="error" :title="error" type="error" :closable="false"/></form><section class="panel"><div class="panel-heading"><h2>{{searched?'查询结果':'最近发布'}}</h2><span>{{reports.length}} 份报告</span></div><el-skeleton v-if="loading" class="padded" :rows="5" animated/><div v-else-if="reports.length" class="report-list"><RouterLink v-for="report in reports" :key="report.id" :to="'/results/'+report.id" class="report-list-item"><span class="report-file-icon"><el-icon><Files/></el-icon></span><div><span class="category-label">{{report.payload.category}}</span><strong>{{report.title}} <span v-if="report.payload.is_demo" class="demo-badge">演示</span></strong><p>{{report.payload.summary}}</p></div><span class="report-level">{{report.payload.level?'L'+report.payload.level+' · ':''}}{{report.payload.level_name}}</span><el-icon><ArrowRight/></el-icon></RouterLink></div><div v-else class="purposeful-empty"><h3>暂无已发布报告</h3><RouterLink to="/submit" class="secondary-link">提交成果</RouterLink></div></section></div></template>
