<script setup lang="ts">
import {computed,ref,onMounted,onUnmounted} from 'vue'
import {api,statusNames,formatDate} from '../api'
import type {Ticket} from '../types'
import QueryHistory from '../components/QueryHistory.vue'
const rows=ref<Ticket[]>([]),error=ref(''),tab=ref('evaluations'),filter=ref('all'),loading=ref(true),selected=ref<{name:string;payload:Record<string,unknown>}|null>(null)
const shown=computed(()=>filter.value==='all'?rows.value:rows.value.filter(x=>x.status===filter.value))
async function load(){try{rows.value=await api('/tickets');error.value=''}catch(e){error.value=(e as Error).message}finally{loading.value=false}}
async function inspect(row:Ticket){try{const submission=await api<{payload:Record<string,unknown>}|null>('/submissions/'+row.id);selected.value={name:row.query,payload:submission?.payload||{supplementary_notes:row.note||'暂无补充说明'}}}catch(e){error.value=(e as Error).message}}
const fields:Record<string,string>={project_name:'所属项目',outcome_name:'成果名称',outcome_type:'成果形态',description:'成果描述',ai_role:'AI 参与环节',organizations:'参与单位',members:'核心成员',related_outputs:'相关成果',metrics_baseline:'指标与基线',external_validation:'外部验证',supplementary_notes:'补充说明',project_start_date:'项目启动日',review_cutoff:'评审截止日',cutoff_basis:'日期依据'}
let timer:ReturnType<typeof setInterval>
onMounted(()=>{load();timer=setInterval(load,8000)});onUnmounted(()=>clearInterval(timer))
</script>
<template><div class="content-page"><div class="page-heading"><div><h1>我的评测</h1></div><RouterLink to="/submit" class="primary-link">提交新成果</RouterLink></div><el-alert v-if="error" :title="error" type="error" :closable="false"/><el-tabs v-model="tab" class="content-tabs"><el-tab-pane label="评测申请" name="evaluations"><section class="panel padded"><div class="table-toolbar"><el-select v-model="filter" aria-label="筛选评测状态" style="width:160px"><el-option label="全部状态" value="all"/><el-option v-for="s in ['pending','processing','review','published','closed']" :key="s" :label="statusNames[s]" :value="s"/></el-select><el-button @click="load">刷新进度</el-button></div><el-skeleton v-if="loading" :rows="4" animated/><div v-else-if="!rows.length" class="purposeful-empty"><h3>暂无评测申请</h3><RouterLink to="/submit" class="secondary-link">提交成果</RouterLink></div><el-table v-else :data="shown" empty-text="此状态下暂无申请"><el-table-column label="成果名称" prop="query" min-width="200"/><el-table-column label="状态" width="115"><template #default="{row}"><el-tag :type="row.status==='published'?'success':'info'">{{statusNames[row.status]}}</el-tag></template></el-table-column><el-table-column label="提交时间" min-width="170"><template #default="{row}">{{formatDate(row.created_at)}}</template></el-table-column><el-table-column label="处理进展" min-width="200"><template #default="{row}">{{row.note||'等待管理员受理'}}</template></el-table-column><el-table-column label="操作" min-width="150"><template #default="{row}"><el-button link type="primary" @click="inspect(row)">提交详情</el-button><RouterLink v-if="row.result_id" :to="'/results/'+row.result_id" class="text-link">查看报告</RouterLink></template></el-table-column></el-table></section></el-tab-pane><el-tab-pane label="报告查询记录" name="queries" lazy><QueryHistory/></el-tab-pane></el-tabs><el-dialog :model-value="!!selected" @close="selected=null" title="成果提交详情" width="min(760px,94vw)"><template v-if="selected"><h2>{{selected.name}}</h2><dl class="submission-details"><template v-for="(label,key) in fields" :key="key"><dt v-if="selected.payload[key]">{{label}}</dt><dd v-if="selected.payload[key]">{{selected.payload[key]}}</dd></template></dl></template></el-dialog></div></template>
