<script setup lang="ts">
import {computed,onMounted,ref} from 'vue'
import {DocumentAdd,ArrowRight,Files} from '@element-plus/icons-vue'
import {api,statusNames,formatDate} from '../api'
import type {Ticket,Result} from '../types'
const tickets=ref<Ticket[]>([]),reports=ref<Result[]>([]),loading=ref(true),error=ref('')
const counts=computed(()=>[{label:'待受理',value:tickets.value.filter(t=>t.status==='pending').length},{label:'评测中',value:tickets.value.filter(t=>t.status==='processing').length},{label:'待审核',value:tickets.value.filter(t=>t.status==='review').length},{label:'已发布',value:tickets.value.filter(t=>t.status==='published').length}])
onMounted(async()=>{try{[tickets.value,reports.value]=await Promise.all([api<Ticket[]>('/tickets'),api<Result[]>('/results')])}catch(e){error.value=(e as Error).message}finally{loading.value=false}})
</script>
<template><div class="content-page dashboard-page"><div class="page-heading"><div><h1>工作台</h1></div><RouterLink to="/submit" class="primary-link"><el-icon><DocumentAdd/></el-icon>提交新成果</RouterLink></div><el-alert v-if="error" :title="error" type="error" :closable="false"/><el-skeleton v-if="loading" :rows="5" animated/><template v-else><section class="overview-strip" aria-label="我的评测进度"><div v-for="item in counts" :key="item.label"><span>{{item.label}}</span><strong>{{item.value}}</strong><small>项成果</small></div></section><div class="dashboard-grid"><section class="panel"><div class="panel-heading"><h2>最近提交</h2><RouterLink to="/tickets" class="text-link">全部评测 <el-icon><ArrowRight/></el-icon></RouterLink></div><div v-if="!tickets.length" class="purposeful-empty"><span class="empty-icon"><el-icon><Files/></el-icon></span><h3>还没有提交成果</h3><RouterLink to="/submit" class="secondary-link">提交第一项成果</RouterLink></div><div v-else class="recent-list"><RouterLink v-for="ticket in tickets.slice(0,5)" :key="ticket.id" to="/tickets" class="recent-item"><div><strong>{{ticket.query}}</strong><small>{{formatDate(ticket.created_at)}}</small></div><el-tag :type="ticket.status==='published'?'success':'info'">{{statusNames[ticket.status]||ticket.status}}</el-tag></RouterLink></div></section></div><section class="panel"><div class="panel-heading"><h2>已发布成果报告</h2><RouterLink to="/library" class="text-link">进入报告库 <el-icon><ArrowRight/></el-icon></RouterLink></div><div v-if="reports.length" class="report-list"><RouterLink v-for="report in reports.slice(0,3)" :key="report.id" :to="'/results/'+report.id" class="report-list-item"><span class="report-file-icon"><el-icon><Files/></el-icon></span><div><strong>{{report.title}} <span v-if="report.payload.is_demo" class="demo-badge">演示</span></strong><p>{{report.payload.summary}}</p></div><span class="report-level">{{report.payload.level?'L'+report.payload.level+' · ':''}}{{report.payload.level_name}}</span><el-icon><ArrowRight/></el-icon></RouterLink></div><p v-else class="empty-inline">暂无已发布报告。</p></section></template></div></template>
